import './globals.css';
import { Open_Sans } from 'next/font/google';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

const openSans = Open_Sans({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={`min-h-screen bg-eerie-black font-${openSans.className} prose dark:prose-invert max-w-full`}>{children}</body>
	</html>
	);
}

